[package]
name = "game"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]

[dependencies]
clippy = { version = "*", optional = true }

[dependencies.world]
path = "../world"

[dependencies.util]
path = "../util"

