[package]
name = "generate"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]

[dependencies]
rand = "0.4.2"
clippy = { version = "*", optional = true }

[dependencies.world]
path = "../world"

