[package]
name = "head"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]

[dependencies]
game  = { path = "../game" }
world = { path = "../world" }
llr   = { path = "../llr" }
util  = { path = "../util" }

