[package]
name = "head"
version = "0.1.0"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]

[dependencies]
sdl2 = { version = "0.31", default-features = false, features = [] }

game  = { path = "../game" }
world = { path = "../world" }
util  = { path = "../util" }

